### DISCUSSION TITLE
About settings for ResNet-18 backbone

### DISCUSSION THREAD

**Discussion by xwjabc** [STVIR/pysot#388] [General] [answered]
Hi, recently I am training the tracker with ResNet-18 backbone. Currently, I simply reuse https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml and modify the   

```
TYPE: "resnet50"
ADJUST:
    KWARGS:
        in_channels: [512, 1024, 2048]
```
to
```
TYPE: "resnet18"
ADJUST:
    KWARGS:
        in_channels: [128, 256, 512]
```
Since ResNet-18 uses BasicBlock which has less channels, I wonder if the channels of MultiRPN should be kept the same (i.e. `RPN.KWARGS.in_channels=[256, 256]`) or reduced (e.g. `RPN.KWARGS.in_channels=[64, 64]`). Thanks!
