### DISCUSSION TITLE
Changing backbone to resnet18

### DISCUSSION THREAD

**Discussion by htet96** [STVIR/pysot#497] [Q&A] [answered]
Hello, how do I modify the code to use the resnet18 backbone? I have already downloaded the pth file from pytorch.

**Comment by ZhiyuanChen** [comment, marked as answer]
in your config,

```
BACKBONE:
    TYPE: "resnet18"
    KWARGS:
        used_layers: [0, 1, 2, 3]
```
