### ISSUE TITLE
Changing backbone to resnet18

### ISSUE THREAD

**Issue by htet96** [STVIR/pysot#490]
Hello, how do I modify the code to use the resnet18 backbone? I have already downloaded the pth file from pytorch.

**Comment by ZhiyuanChen** [comment]
in your config,

```
BACKBONE:
    TYPE: "resnet18"
    KWARGS:
        used_layers: [0, 1, 2, 3]
```
